#! /bin/sh

bspc rule -a TelegramDesktop desktop='^2'

pgrep -x sxhkd > /dev/null || sxhkd -f &

$HOME/.config/polybar/scripts/launch.sh &

if ! pgrep -x "picom" > /dev/null; then
    picom &
fi

xsetroot -cursor_name left_ptr &

if ! pgrep -x "setxkbmap" > /dev/null; then
    setxkbmap -model pc105 -layout us,ru -option grp:caps_toggle
fi

if ! pgrep -x "zen-bin" > /dev/null; then
    zen-browser &
fi

if ! pgrep -x "dunst" > /dev/null; then
    dunst &
fi

if ! pgrep -x "telegram-desktop" > /dev/null; then
    telegram-desktop &
fi

if ! pgrep -x "clipcatd" > /dev/null; then 
    clipcatd &
fi

libinput-gestures-setup start &
	
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

/usr/bin/nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6 7 

bspc config window_gap 7
bspc config border_width 2

bspc config split_ratio 0.5

bspc config normal_border_color "#b7bdf8"
bspc config active_border_color "#b7bdf8"
bspc config focused_border_color "#b7bdf8"
bspc config presel_feedback_color "#b7bdf8"

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config single_monocle           true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  true
